package com.novacorp.inmonode.inmonodebackend.financial.interfaces.rest.resources;

import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Positive;

import java.util.UUID;

/**
 * @param documentId id generated by the back office for this upload; send the same one to issue the contract
 * @param sizeBytes  exact size of the PDF, up to 10 MB (10485760 bytes)
 */
public record ContractDocumentResource(@NotNull UUID documentId, @NotNull @Positive Long sizeBytes) {
}
